import { api } from '../api';
import { usePolling } from '../hooks';
import { at, bytes, fmt, list, num, obj, pct, state, str, time } from '../data';
import type { Data } from '../types';
import { ActionButton, DataTable, Disclosure, ErrorState, JsonDetails, Loading, SectionLabel, Signal, StageTrack, Toggle } from '../components/ui';

const reasonLabels:Record<string,string>={'history-guided':'이전 시험 성적 반영','new-expert-probe':'새 전문가 첫 시험',exploration:'새 조합 탐색','successful-mutation-combination':'성적이 좋았던 변경 2개 조합'};
export function Assembly(){
 const q=usePolling('/api/assembly/status',3000),a=q.data;
 if(!a)return q.error?<ErrorState message={q.error} retry={q.refresh}/>:<Loading/>;
 const c=a.candidate||{},ch=a.champion||{},settings=obj(a.settings),worker=obj(a.worker),queue=a.queue||[],history=a.history||[],newIds=list(a.new_experts).map(x=>typeof x==='string'?x:str(obj(x).id)), candidateIds=new Set(list(c.enabled_experts).map(x=>str(x))),championIds=new Set(list(ch.enabled_experts).map(x=>str(x)));
 const replay=obj(obj(c.scores).replay),paper=obj(obj(c.scores).paper);
 return <>
  {q.error&&<ErrorState message={q.error} retry={q.refresh}/>}
  <section className="assembly-control"><div className="assembly-automation"><header><SectionLabel eyebrow="AUTOMATED ASSEMBLY" title="자동 조립 제어" detail="Expert 원본 가중치는 공유하고 후보별 recipe와 작은 학습 state만 저장합니다."/><Signal label="자동조립" value={a.enabled?'실행 중':'정지'} tone={a.enabled?'good':'neutral'}/></header><div className="action-row"><ActionButton label="자동조립 시작" path={api.assembly('start')} disabled={!!a.enabled}/><ActionButton label="자동조립 정지" path={api.assembly('stop')} disabled={!a.enabled}/><ActionButton label="새 Candidate 즉시 생성" path={api.assembly('generate')}/><ActionButton label="현재 Candidate 시험 시작" path={api.assembly('trial/start')} disabled={!a.candidate||!!worker.alive}/><ActionButton label="현재 Candidate 시험 정지" path={api.assembly('trial/stop')} disabled={!worker.alive}/><ActionButton label="현재 Candidate 탈락 · 다음 후보" path={api.assembly('next')} tone="warn"/></div><div className="assembly-switches"><Toggle label="자동 Candidate 교체" enabled={!!settings.auto_replace} path={api.assembly('settings')} field="auto_replace"/><Toggle label="자동 승격" enabled={!!settings.auto_promote} path={api.assembly('settings')} field="auto_promote"/><Toggle label="새 Expert 자동감지" enabled={!!settings.detect_experts} path={api.assembly('settings')} field="detect_experts"/></div></div>
   <div className="assembly-counts">{[['Champion',str(ch.candidate_id)],['현재 Candidate',str(c.candidate_id)],['대기 후보',fmt(queue.length,0)],['누적 시험',fmt(a.experiments,0)],['승격 / 탈락',fmt(a.promotions,0)+' / '+fmt(a.rejections,0)],['새 Expert',fmt(newIds.length,0)]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div>
  </section>
  <section className="assembly-pipeline"><SectionLabel eyebrow="CANDIDATE LIFECYCLE" title="Champion에서 다음 후보까지"/><StageTrack steps={[{label:'Champion recipe',detail:str(ch.candidate_id),state:'done'},{label:'변경 조합 생성',detail:str(c.mutation_description,'다음 recipe 대기'),state:c.candidate_id?'done':'waiting'},{label:'Replay 예선',detail:pct(at(c,'scores.replay.candidate.net_return')),state:c.evaluation_state==='replay_testing'?'active':replay.candidate?'done':'waiting'},{label:'Paper 비교',detail:pct(at(c,'scores.paper.delta'))+' Champion 대비',state:c.evaluation_state==='paper_testing'?'active':paper.candidate?'done':'waiting'},{label:'승격 · 탈락',detail:state(c.evaluation_state),state:c.evaluation_state==='promoted'?'done':c.evaluation_state==='rejected'?'blocked':'waiting'}]}/></section>
  <section className="candidate-focus"><header><SectionLabel eyebrow="ACTIVE RECIPE" title={'Candidate · '+str(c.candidate_id)} detail={str(c.reason,typeof worker.message==='string'?worker.message:'다음 평가 대기')}/><Signal label="평가 단계" value={state(c.evaluation_state)} tone={worker.alive?'good':'neutral'}/></header><p className="trial-reason">{str(c.mutation_description,'아직 Candidate가 생성되지 않았습니다.')}</p><p className="subtle">생성 이유: {reasonLabels[str(c.generation_reason)]||str(c.generation_reason)} · 부모 {str(c.parent_id)} · 생성 {time(c.created_at)} · 학습 state {bytes(a.candidate_state_bytes)} · 전체 checkpoint 복제 {fmt(a.checkpoint_copies,0)}개</p><div className="phase-score-grid">{([['Replay 예선',replay],['Paper 비교',paper]] as [string,Data][]).map(([title,score])=><article className="phase-score" key={title}><header><b>{title}</b><strong className={num(score.delta)<0?'negative':'positive'}>{pct(score.delta)} 차이</strong></header><DataTable headers={['측정값','Candidate','Champion']} rows={['net_return','max_drawdown','trades','fees','seconds'].map(key=>[{net_return:'비용 차감 수익률',max_drawdown:'최대 손실폭',trades:'체결',fees:'비용',seconds:'소요 시간'}[key],key==='net_return'||key==='max_drawdown'?pct(obj(score.candidate)[key]):fmt(obj(score.candidate)[key],key==='seconds'?3:0),key==='net_return'||key==='max_drawdown'?pct(obj(score.champion)[key]):fmt(obj(score.champion)[key],key==='seconds'?3:0)])}/></article>)}</div></section>
  <section className="assembly-recipes"><SectionLabel eyebrow="EXPERT COMBINATION" title="전문가 조립표" detail="runtime Registry를 읽어 목록을 자동 구성합니다."/><DataTable headers={['Expert','Champion','Candidate','역할','담당 universe','이번 실행 선택','갱신 주기']} rows={(a.experts||[]).map(e=>{const id=str(e.id),universe=list(e.universe),selected=list(worker.selected_experts).map(x=>str(x)).includes(id);return[<><b>{str(e.name)}</b>{newIds.includes(id)&&<span className="new-tag">NEW</span>}</>,championIds.has(id)?'사용':'OFF',candidateIds.has(id)?'사용':'OFF',str(e.role),universe.length?universe.slice(0,4).map(x=>str(x)).join(', '):'범용 입력',selected?'선택됨':'—','Champion '+fmt(at(ch,'refresh_seconds.'+id),0)+' · 후보 '+fmt(at(c,'refresh_seconds.'+id),0)+'초'];})}/></section>
  <section className="assembly-history"><SectionLabel eyebrow="EXPERIMENT TRACE" title="후보 queue · 시험 history"/><div className="assembly-queues"><DataTable headers={['대기 Candidate','부모','변경','상태','생성 시각']} rows={queue.map(x=>[str(x.candidate_id),str(x.parent_id),str(x.mutation_description),state(x.evaluation_state),time(x.created_at)])}/><DataTable headers={['시각','후보','결과','변경','판정 이유','Paper 차이']} rows={history.slice(-40).reverse().map(h=>[time(h.time||h.timestamp||h.updated_at||h.created_at),str(h.candidate_id||at(h,'recipe.candidate_id')),state(h.event||h.evaluation_state||h.state),str(h.mutation),str(h.reason||h.message),pct(at(h,'scores.paper.delta'))])}/></div><Disclosure title="Recipe · worker · history 상세"><JsonDetails title="현재 recipe와 score 원본" data={c}/><JsonDetails title="자동조립 상태" data={{settings,worker,registry_versions:a.registry_versions,history_stats:a.history_stats}}/></Disclosure></section>
 </>;
}
